### ISSUE TITLE
Containarize it?

### ISSUE THREAD

**Issue by Jacinto27** [polybit-tech/downloads-segregator#1]
I don't really like downloading random python libraries on my installation. Can you implement docker and containarize the project?

**Comment by 0xPolybit** [comment]
well, this was supposed to be a discontinued project.
but you interested in it, lemme see if i can dockerize the project. will get back to you later.

**Comment by 0xPolybit** [comment]
well, turns out docker isnt working as expected in my machine for a while now. i will mark this issue as not planned for now, but in the case that i can finally dockerize it, ill be sure to reopen this issue and close it as completed. till then, thanks for noticing my project.

**Comment by Jacinto27** [comment]
I can try to dockerize it for you, can I?

**Comment by 0xPolybit** [comment]
sure, fork it and send a pull request.
